version: '2'

services:

  redisdb:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - shared-net

  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    networks:
      - shared-net
    volumes:
    - ./postgres-data:/var/lib/postgresql/data


  app:
      image: book-online-spring-boot
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - 8082:8080
      depends_on:
       # - mysqldb
        - db
      environment:
      #  - spring.datasource.url=jdbc:mysql://mysqldb:3306/book_online
       # - SERVER_PORT=8082
        #- spring.redis.host=redis
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/book_online?createDatabaseIfNotExist=true
        - SPRING_DATASOURCE_USERNAME=compose-postgres
        - SPRING_DATASOURCE_PASSWORD=compose-postgres
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      #  - spring.redis.port=6379
      #  - spring.datasource.username=root
      #  - spring.datasource.password=1234
      restart: always
      networks:
        - shared-net

networks:
  shared-net:
    driver: bridge
