version: '3.8'

services:

  redisdb:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - shared-net

  mysqldb:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: book_online
      MYSQL_USER: root
    ports:
      - "3366:3306"
    networks:
      - shared-net
    volumes:
      - ./mysql/data:/backup



  app:
    image: book-online-spring-boot
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - mysqldb
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/book_online
      - SERVER_PORT=8082
      - spring.redis.host=redis
      - spring.redis.port=6379
      - spring.datasource.username=root
      - spring.datasource.password=1234
    restart: always
    networks:
      - shared-net

networks:
  shared-net:
    driver: bridge

